apiVersion: v1
kind: Service
metadata:
  name: demowk1
  namespace: multi-stage-project-ns
spec:
  type: LoadBalancer
  selector:
    app: demowk1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080